### ISSUE TITLE
Plugin must not request permissions when instantiated

### ISSUE THREAD

**Issue by ened** [hemanthrajv/flutter_compass#12]
If at all, this should be requested when the user starts the scan.

Library users are encouraged to include a plugin like `permission_handler` to retrieve what is needed.

Will prepare a PR.

**Comment by hemanthrajv** [comment]
Makes sense 👍

**Comment by ened** [comment]
@hemanthrajv btw, I can detect the heading without the need for location permissions.. is this old code which could be removed?
