### ISSUE TITLE
FlutterCompass doesn't work in Redmi 6

### ISSUE THREAD

**Issue by mnshaikna** [hemanthrajv/flutter_compass#15]
I get 'E/SensorManager(30827): sensor or listener is null' error while I use FlutterCompass in Redmi 6.

It works in other devices as of now. Is it a known issue?

**Comment by bhanuka96** [comment]
> I get 'E/SensorManager(30827): sensor or listener is null' error while I use FlutterCompass in Redmi 6.
> 
> It works in other devices as of now. Is it a known issue?

Did you find a solution for this?

**Comment by hemanthrajv** [comment]
Fixed by #62
