### ISSUE TITLE
flutter_compass/flutter_compass-Swift.h' file not found

### ISSUE THREAD

**Issue by dark-chocolate** [hemanthrajv/flutter_compass#25]
**Screenshot:** 
![image](https://user-images.githubusercontent.com/40364434/72729651-f41b1880-3b8f-11ea-92ac-9c831df3093a.png)

**Version:** 
0.3.4

**Flutter doctor:** 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.14.1, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by hemanthrajv** [comment]
The `flutter_compass` uses `Swift` for iOS. If your iOS project uses objective-c, please try enabling swift support.

Also check: #3

**Comment by dark-chocolate** [comment]
Ok, I'll take a look at it, closing it for now.
