### ISSUE TITLE
java.lang.IllegalStateException: sensorManager.getDefaultSensor(sensorType) must not be null in Flutter

### ISSUE THREAD

**Issue by mohammednabil95** [hemanthrajv/flutter_compass#27]
I have build a flutter app which has features like showing qibla direction with the help of flutter_compass dependencies. This App works fine in newest versions of Android Devices but if i try to install this app in older versions (API 16, API 17) it shows "Unfortunately this App has Stopped". I checked in logcat it shows "java.lang.IllegalStateException: sensorManager.getDefaultSensor(sensorType) must not be null". So do i need to add some native code in android folder or dependencies in buildgradle ?

**Comment by medyas** [comment]
@mohammednabil95 You should probably first check whether the devices has the sensor hardware, and  this is what causing your crashes as the device does not have any hardware and your trying to access it anyway.

**Comment by medyas** [comment]
@mohammednabil95 checkout this package which i developed [flutter_qiblah](https://pub.dev/packages/flutter_qiblah)
Its has a method which allows you to check whether the device has the required hardware: 
`final _deviceSupport = FlutterQiblah.androidDeviceSensorSupport();`

**Comment by ebjerkelund** [comment]
I have a similar issue on a Samsung 5.1.1 device. Other compass apps work fine.

Related to #39 ? The compass apps that do work are using Sensor.TYPE_ACCELEROMETER and Sensor.TYPE_MAGNETIC_FIELD

**Comment by hemanthrajv** [comment]
Fixed by #62
