### ISSUE TITLE
android shows magnetic iOS shows true

### ISSUE THREAD

**Issue by robcleghorn** [hemanthrajv/flutter_compass#31]
This is a real flaw .

**Comment by robcleghorn** [comment]
this like looks suspicious

`heading = newHeading.trueHeading > 0 ? newHeading.trueHeading : newHeading.magneticHeading; `

**Comment by hemanthrajv** [comment]
Nice catch, thanks for letting me know. I think it should be only `heading = newHeading.trueHeading` right? 
Can you place a PR with correct implementation?

**Comment by robcleghorn** [comment]
Think it should be (sorry i'm not a swift developer)
`heading = newHeading.magneticHeading;`

https://developer.apple.com/documentation/corelocation/clheading/1423763-magneticheading

**Comment by hemanthrajv** [comment]
That would give head with respect to magnetic north. Not the actual north.

**Comment by robcleghorn** [comment]
Correct, which is what we want, no?  I assume you want it to work like Android?

**Comment by hemanthrajv** [comment]
No, I don't think so. The heading zero should indicate the direction true North, using magentic heading would invert that. 

If Location updates are enabled, true heading to be used else should fallback to magnetic heading.

For now, I think I can update the docs indicating the behaviour.
Later can update to invert magnetic heading to match true heading, but magnetic declination can have effect.

**Comment by robcleghorn** [comment]
I disagree. This is fundamental navigation, I have no idea what you mean by
invert.  My PR makes iOS return magnetic heading, I can confirm it works
well and most importantly it makes iOS and Android behave the same.  Where
I live we have a 20 degree declination so your bug is pretty obvious here.
You should never switch headings between these automatically unless you
want to cause major issues for anyone using your library and their users.

**Comment by hemanthrajv** [comment]
@robcleghorn , my apologies. I think you are right. I mistook magnetic for true, so silly of me. Thanks for the PR. Accepting now!

Closes #32
