### ISSUE TITLE
rxdart needs update

### ISSUE THREAD

**Issue by sgehrman** [hemanthrajv/flutter_compass#34]
Because flutter_compass 0.4.1 depends on rxdart ^0.23.1 and no versions of flutter_compass match >0.4.1 <0.5.0, flutter_compass ^0.4.1 requires rxdart ^0.23.1.
So, because therapist_training depends on both rxdart ^0.24.0 and flutter_compass ^0.4.1, version solving failed.

**Comment by hemanthrajv** [comment]
Sorry for the delay. Updated the libs, please use latest version.
