### ISSUE TITLE
[Android] Doesn't work in landscape

### ISSUE THREAD

**Issue by lukepighetti** [hemanthrajv/flutter_compass#41]
This package does not work as expected on Android when the device is in landscape mode. The heading is affected by the device depending on how flat you are holding it.

It does, however, work as expected on iOS in landscape mode.

related: https://github.com/hemanthrajv/flutter_compass/issues/33

**Comment by gabeschine** [comment]
FYI - this should now be fixed.

**Comment by MooNag** [comment]
This issue should be closed if it is fixed @lukepighetti

**Comment by lukepighetti** [comment]
I can't test it but I'd be happy to close it!
