### ISSUE TITLE
I'd like to take over this package

### ISSUE THREAD

**Issue by lukepighetti** [hemanthrajv/flutter_compass#43]
Hi @hemanthrajv ,

I'd like to take over this package. I will maintain it and add features. If this is agreeable to you, please transfer this repo to https://github.com/lukepighetti and add `lukepighetti@gmail.com` to the uploaders.

Thanks,
Luke

**Comment by hemanthrajv** [comment]
No idea in transferring as of now, sorry.

**Comment by lukepighetti** [comment]
No problem, best of luck!
