### ISSUE TITLE
Migration to sound null safety

### ISSUE THREAD

**Issue by martypapa** [hemanthrajv/flutter_compass#49]
Migration to Sound Null Safety should be added. The rx-dart dependency has been migrated, so there are no blockers here.

Example implementation from fork: https://github.com/martypapa/flutter_compass

**Comment by MooNag** [comment]
Not repo owner; Is this a full null safety migration in your fork? If so you could create a PR for it and I would be willing to look over it as a second check before the repo owner merges it. Ping me in the description if you create a PR!

**Comment by iqfareez** [comment]
Any update on this?

**Comment by hemanthrajv** [comment]
Verison 6.0.0 and above supports null safety
