### ISSUE TITLE
Crashes app when added as dependency - no actual code in app!

### ISSUE THREAD

**Issue by relativityboy** [hemanthrajv/flutter_compass#5]
W/Flutter 1.0 adding this plugin as a dependency `flutter_compass: ^0.0.2` causes my app to crash. No code referencing it anywhere. No log errors just the `Syncing files ...` message, then this:
<img width="327" alt="screen shot 2018-12-10 at 11 57 18 pm" src="https://user-images.githubusercontent.com/599528/49781510-a3709500-fcd8-11e8-981d-6154fb545bd8.png">

Remove the dependency, the app runs fine.

**Comment by hemanthrajv** [comment]
Try `flutter clean ` , then `flutter packages get ` and then `flutter run`. Hope after adding dependency, you tried hot reload.

**Comment by relativityboy** [comment]
Just did flutter clean, flutter packages get, flutter run. Same outcome.

Yes. Before posting the issue I'd done a hot reload, cold load, restarted the simulated device. 3ish times.

:(

**Comment by hemanthrajv** [comment]
Can you share logs if any?

**Comment by relativityboy** [comment]
Captain obvious here.. 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.boop.fluttercompassapp/com.boop.fluttercompassapp.MainActivity}: java.lang.IllegalStateException: sensorManager.getDefaultSensor(sensorType) must not be null
```

🤦‍♂️

**Comment by relativityboy** [comment]
It leads me to wonder though, should the lib even have code that runs on init of app? I'd normally do that kind of thing on instantiation of an object from the lib... via factory method or something.

**Comment by relativityboy** [comment]
Did a search for `sensorManager.getDefaultSensor(sensorType)` and in `FlutterCompassPlugin.kt` I see
```
 private var mAzimuth = 0.0 // degree
  private var newAzimuth = 0.0 // degree
  private var mFilter = 1f
  private var sensorEventListener: SensorEventListener? = null
  private val sensorManager: SensorManager
  private val sensor: Sensor
  private val orientation = FloatArray(3)
  private val rMat = FloatArray(9)
```
So, that fix isn't in the published version. 

A quick check of this repo's `pubspec.yaml` file shows `version: 0.0.1` don't know if that affects your publishing (coming from npm land here) but could be worth updating to 0.0.3? (or 0.0.2 if it never really got pushed.)

**Comment by hemanthrajv** [comment]
Thanks for noticing. Seems I published to pub directly without pushing changes to git. My bad. I've pushed version [0.0.3](https://pub.dartlang.org/packages/flutter_compass). Please upgrade dependency. Closing this referring the above, please do not hesitate to reopen this if you still run through the same.
