### ISSUE TITLE
rxdart needs update

### ISSUE THREAD

**Issue by BertCasteel** [hemanthrajv/flutter_compass#50]
https://pub.dev/packages/rxdart now has version ^0.25.0. 
My project depends on https://pub.dev/packages/camerawesome and flutter_compass, but camerawesome uses ^0.25.0 whereas flutter_compass is still on ^0.24.1.

**Comment by b-jan** [comment]
Same issue here, did you open a PR with version update?

**Comment by b-jan** [comment]
@hemanthrajv Do you plan to make a null safe update?
With an upgrade of rxdart too :)

**Comment by hemanthrajv** [comment]
Published the version [`0.6.0`](https://pub.dev/packages/flutter_compass)
