### ISSUE TITLE
Example does not work from Flutter Pub

### ISSUE THREAD

**Issue by beachpebble** [hemanthrajv/flutter_compass#55]
I also tried to make this work from the example on Flutter Pub but it got stuck while testing after pushing one of your buttons and now no matter what I it stays stuck in that state. I have deleted the code and run it again and everytime it returns to this state. The buttons do not return. The example on Flutter Pub is not functional and the example on GitHub is deprecated.

![Screen Shot 2021-04-18 at 9 06 50 AM](https://user-images.githubusercontent.com/10665584/115152420-cee0b880-a025-11eb-9633-0d41c31b9ff7.png)

**Comment by hemanthrajv** [comment]
Closed by #62
