### ISSUE TITLE
The plugin `flutter_compass` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by dark-chocolate** [hemanthrajv/flutter_compass#62]
I get this error on running `flutter pub get`. 

> The plugin `flutter_compass` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

### Package version:
`^0.6.1`

### Flutter version: 
```
Flutter 2.5.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 184e5871be (3 days ago)
Tools • Dart 2.14.0 (build 2.14.0-350.0.dev)
```

**Comment by iqfareez** [comment]
Please, this plugin need to be migrated to Android Embedding V2 😞

**Comment by AekaderFELLAGUE** [comment]
I'm facing the same problem...

**Comment by sergey-s-moiseev** [comment]
This issue is very critical for me! Lot of [Flutter Map](https://pub.dev/packages/flutter_map ) Plugins related on this module! Please fix it asap!

**Comment by peterkuch** [comment]
> I get this error on running `flutter pub get`.
> 
> > The plugin `flutter_compass` uses a deprecated version of the Android embedding.
> > To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
> 
> ### Package version:
> `^0.6.1`
> 
> ### Flutter version:
> ```
> Flutter 2.5.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
> Framework • revision 184e5871be (3 days ago)
> Tools • Dart 2.14.0 (build 2.14.0-350.0.dev)
> ```

me too The plugin `flutter_compass` uses a deprecated version of the Android embedding.

**Comment by nasirmalik01** [comment]
**

**Comment by ikallali** [comment]
+1 any  progress ?
