### ISSUE TITLE
Version 0.7.0 is extremely laggy on Android devices

### ISSUE THREAD

**Issue by 15tariqj** [hemanthrajv/flutter_compass#83]
Not sure why this has occurred, reverting to 0.6.1 works, whereas 0.7.0 is extremely laggy on Android devices (is fine on iOS)

**Comment by guccibase** [comment]
Was just about to report this too. Experienced it with my app and verified it on Pillars as well before realizing its an issue with the package

**Comment by nukeolay** [comment]
Find a solution.
Version in this GitHub repository is already fixed, but is not published to pub.dev, so you can simply import to your project directly from this repository instead of pub.dev. Just replace "flutter_compass: ^0.7.0" in your pubspec.yaml with this:
flutter_compass:
    git:
      url: https://github.com/hemanthrajv/flutter_compass.git
      ref: master

**Comment by 15tariqj** [comment]
Thank you!
