### ISSUE TITLE
Getting null values on iOS devices and Simulator in debug mode

### ISSUE THREAD

**Issue by mmahgoub** [hemanthrajv/flutter_compass#88]
I ran the example on the Simulator and on iPhone but I get null values and `snapshot.ConnectionState` is stuck in `ConnectionState.waiting`

version 0.7.0

**Comment by Metaphysics0** [comment]
Same

**Comment by mmahgoub** [comment]
I was using a virtual machine for testing but with a physical device it worked fine. The initial value if heading is null and you have to poke the phone for values to come from the sensor.

As gor the simulator I don't it has the sensors emulation.

**Comment by mmahgoub** [comment]
I am closing this since i knew what was the problem
