### ISSUE TITLE
flutter compass does not specify a swift version

### ISSUE THREAD

**Issue by TeamCommonwealth** [hemanthrajv/flutter_compass#9]
it is giving me this error **" [!] Unable to determine Swift version for the following pods:
    - `flutter_compass` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod."**

I even updated my cocoa pods also did a pod install which gave me the same error .
I also changed the pod file and put the target swift version for flutter compass but still the issue is not resolved . Could you please look into that and help me asap.
ThankYou

**Comment by hemanthrajv** [comment]
Please share steps to reproduce. Does it happen with just creating new
project?

**Comment by TeamCommonwealth** [comment]
I am attaching all the steps 
![package](https://user-images.githubusercontent.com/48297849/54309139-297cd000-4595-11e9-8d01-ac4b467246d4.png)
![pubspec](https://user-images.githubusercontent.com/48297849/54309146-300b4780-4595-11e9-9923-91fa22a5f6c6.png)
![code](https://user-images.githubusercontent.com/48297849/54309155-3699bf00-4595-11e9-98c2-5644bfa4ad96.png)
![Podfile](https://user-images.githubusercontent.com/48297849/54309160-38fc1900-4595-11e9-8679-43cfcaa2b019.png)
![debug with error](https://user-images.githubusercontent.com/48297849/54309166-3b5e7300-4595-11e9-8d44-bed7083c27a5.png)

**Comment by TeamCommonwealth** [comment]
@hemanthrajv thank you it works fine now
